<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clase 31 - Manejando Errores</title>
</head>
<body>
    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script>
        const API_URL = 'https://swapi.dev/api/';
        const PEOPLE_URL = 'people/:id';
        const OPTS = { crossDomain: true };
        
        
        function obtenerPersonaje(id, callback) {
            console.log(id);
            const URL = `${API_URL}${PEOPLE_URL.replace(':id', id)}`;
            
            $
            .get(URL, OPTS, callback)
            .fail(() => {
                console.log(`Sucedi√≥ un error. No se pudo obtener el personaje ${id}.`);
            });
        }

        obtenerPersonaje(1, function (personaje) {
            console.log(`Hola. Yo soy ${personaje.name}`);

            obtenerPersonaje(2, function (personaje) {
                console.log(`Hola. Yo soy ${personaje.name}`);

                obtenerPersonaje(3, function (personaje) {
                    console.log(`Hola. Yo soy ${personaje.name}`);

                    obtenerPersonaje(4, function (personaje) {
                        console.log(`Hola. Yo soy ${personaje.name}`);

                        obtenerPersonaje(5, function (personaje) {
                            console.log(`Hola. Yo soy ${personaje.name}`);
                        });
                    });
                });
            })
        });
        
        // No funciona esta forma, ya que llega primero el 2 que el 1
        // obtenerPersonaje(1, obtenerPersonaje(2));
        
    </script>
</body>
</html>